### PR TITLE
Bug fixes app 6

### PR DESCRIPTION
**Pull request by DylanHainsworthNHSD**
Bug updates to App6
- https://nhsd-jira.digital.nhs.uk/browse/NBRS-3172 
- https://nhsd-jira.digital.nhs.uk/browse/NBRS-3173
- https://nhsd-jira.digital.nhs.uk/browse/NBRS-3174
- https://nhsd-jira.digital.nhs.uk/browse/NBRS-3175
- https://nhsd-jira.digital.nhs.uk/browse/NBRS-3176

Made the workflow image clickable on "How it Works" this makes it easier to see in a second window.

### CODE REVIEW

**Review by Goslinl — APPROVED** [review]

**Comment by DylanHainsworthNHSD** [comment]
@julieharris37 Sorry the Task change is in this branch. I left the comment on the wrong Pull Request

**Comment by julieharris37** [comment]
If the referral Sender may need to cancel a Referral, for example the patient calls back and says they do not require an ambulance, they may send a Cancellation

Change may need to needs

Assume NBRS 3176 is in another Pull Request

**Comment by DylanHainsworthNHSD** [comment]
Change above made for Cancellation Text. NBRS-3176 is in this PR.

**Comment by julieharris37** [comment]
All good now

**Pull request merged**
